export const Films = [
  {
    id: 1,
    img: "assets/images/1917.jpg",
    title: "1917",
    year: "2019",
    nation: "USA",
    trailer: "https://www.youtube.com/embed/YqNYrYUiMfg?rel=0",
  },
  {
    id: 2,
    img: "assets/images/annette.jpg",
    title: "Annette",
    year: "2019",
    nation: "USA",
    trailer: "https://www.youtube.com/embed/YqNYrYUiMfg?rel=0",
  },
  {
    id: 3,
    img: "assets/images/back-to-the-future.jpg",
    title: "Back to the future",
    year: "1985",
    nation: "USA",
    trailer: "https://www.youtube.com/embed/YqNYrYUiMfg?rel=0",
  },
  {
    id: 4,
    img: "assets/images/black-panther.jpg",
    title: "Black Panther",
    year: "2018",
    nation: "USA",
    trailer: "https://www.youtube.com/embed/YqNYrYUiMfg?rel=0",
  },
  {
    id: 5,
    img: "assets/images/fast.jpg",
    title: "Fast and Furious X",
    year: "2023",
    nation: "USA",
    trailer: "https://www.youtube.com/embed/YqNYrYUiMfg?rel=0",
  },
  {
    id: 6,
    img: "assets/images/harry.png",
    title: "Harry Potter and The Deathly Hallows - 2",
    year: "2011",
    nation: "UK",
    trailer: "https://www.youtube.com/embed/YqNYrYUiMfg?rel=0",
  },
  {
    id: 7,
    img: "assets/images/harry2.jpg",
    title: "Harry Potter and The Philosopher's Stone",
    year: "2001",
    nation: "UK",
    trailer: "https://www.youtube.com/embed/YqNYrYUiMfg?rel=0",
  },
  {
    id: 8,
    img: "assets/images/john-wick.jpg",
    title: "John Wick",
    year: "2014",
    nation: "USA",
    trailer: "https://www.youtube.com/embed/YqNYrYUiMfg?rel=0",
  },
  {
    id: 9,
    img: "assets/images/joker.jpg",
    title: "Joker",
    year: "2019",
    nation: "USA",
    trailer: "https://www.youtube.com/embed/YqNYrYUiMfg?rel=0",
  },
];
